Repository codeit-sprint-part3-6team/project, pull requests merged in 2024-12, with the labels that each got.

#6 에어비엔비 린트 적용, 테스트
  .eslintrc.json
  next.config.ts
  package-lock.json
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: ⚙️ 세팅

#9 중간 테스트 배포 브랜치
  .eslintrc.json
  .github/pull_request_template.md
  .prettierrc.json
  README.md
  build.sh
  next.config.ts
  package-lock.json
  package.json
  public/favicon.ico
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/globals.css
Labels: ⚙️ 세팅

#10 default 브랜치 feature로 변경
  README.md
  src/pages/_document.tsx
  src/pages/index.tsx
Labels: ⚙️ 세팅

#12 이슈 생성 테스트
  src/pages/index.tsx
Labels: 🧪 테스트

#18 이슈 생성 테스트
  src/pages/index.tsx
Labels: 🧪 테스트

#17 📝 Prettier, Lint 추가
  .eslintrc.json
  .prettierrc
  src/pages/_document.tsx
Labels: ⚙️ 세팅

#14 test
  tsconfig.json
Labels: 🧪 테스트

#24 #23 feat 폴더 구조
  public/images/.gitkeep
  src/components/common/.gitkeep
  src/components/common/button/.gitkeep
  src/components/common/card/.gitkeep
  src/components/common/dropdown/.gitkeep
  src/components/common/input/.gitkeep
  src/components/common/modal/.gitkeep
  src/components/common/navbar/.gitkeep
  src/components/common/pagination/.gitkeep
  src/components/common/sidebar/.gitkeep
  src/components/common/toast/.gitkeep
  src/components/product/auth/.gitkeep
  src/components/product/dashboard/.gitkeep
  src/components/product/landing/.gitkeep
  src/components/product/mydashboard/.gitkeep
  src/components/product/mypage/.gitkeep
  src/hooks/.gitkeep
  src/pages/api/.gitkeep
  src/pages/dashboard/.gitkeep
  src/pages/mydashboard/.gitkeep
  src/pages/mypage/.gitkeep
  src/pages/signin/.gitkeep
  src/pages/signup/.gitkeep
  src/reducer/.gitkeep
  src/type/.gitkeep
  src/utils/.gitkeep
Labels: ⚙️ 세팅

#22 test: 이슈 생성 테스트
  src/styles/globals.css
Labels: 🧪 테스트

#32 디스코드 PR 알림 연동
  README.md
Labels: ⚙️ 세팅, 📝 문서

#37 📦 SVGR 추가
  global.d.ts
  next.config.ts
  package-lock.json
  package.json
  src/pages/index.tsx
  tsconfig.json
Labels: 📦 패키지

#35 ✨ 공통컴포넌트 globalstyle
  package-lock.json
  package.json
  public/fonts/.gitkeep
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-SemiBold.woff2
  src/pages/_app.tsx
  src/styles/fonts.css
  src/styles/fonts/Pretendard-Bold.subset.woff
  src/styles/fonts/Pretendard-Bold.subset.woff2
  src/styles/fonts/Pretendard-Medium.subset.woff
  src/styles/fonts/Pretendard-Medium.subset.woff2
  src/styles/fonts/Pretendard-Regular.subset.woff
  src/styles/fonts/Pretendard-Regular.subset.woff2
  src/styles/fonts/Pretendard-SemiBold.subset.woff
  src/styles/fonts/Pretendard-SemiBold.subset.woff2
  src/styles/globals.css
Labels: 📁 컴포넌트

#41 #40 버튼공통 컴포넌트 global style 적용
  package-lock.json
  src/components/common/button/Button.module.css
  src/components/common/button/CDSButton.tsx
Labels: 💫 업데이트

#38 #33 공통컴포넌트 input이메일 비밀번호
  src/components/common/input/AuthInput.module.css
  src/components/common/input/AuthInput.tsx
  src/components/common/input/test_AuthInput.tsx
  src/pages/api/axios.ts
Labels: 📁 컴포넌트

#42 공통컴포넌트 globalstyle
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-SemiBold.woff2
  src/pages/home/.gitkeep
  src/styles/fonts.css
Labels: 💄 스타일

#47 #30 공통컴포넌트 Sidebar
  public/images/img_textlogo.svg
  src/components/common/sidebar/Sidebar.module.css
  src/components/common/sidebar/Sidebar.tsx
  src/lib/instance.ts
  src/lib/mydashboard/getDashboard.ts
  src/pages/test.tsx
  src/styles/globals.css
Labels: 📁 컴포넌트

#46 💄 폰트 css 수정
  src/components/common/button/Button.module.css
Labels: 💄 스타일

#49 ✨ Chip 컴포넌트 추가
  src/components/common/chip/Chip.module.css
  src/components/common/chip/Chip.tsx
  src/components/common/chip/helper.ts
  src/type/chip.ts
Labels: 📁 컴포넌트

#53 #52 공통 모달 오버레이 모달가입완료 비밀번호 불일치 중복 이메일
  src/components/common/modal/auth/AuthModal.module.css
  src/components/common/modal/auth/AuthModal.tsx
  src/components/common/modal/auth/Test_AuthModal.tsx
  src/components/common/modal/delete-cards/DeleteCardsModal.module.css
  src/components/common/modal/delete-cards/DeleteCardsModal.tsx
  src/components/common/modal/delete-cards/Test_DeleteCardsModal.tsx
  src/components/common/modal/overlay-container/OverlayContainer.module.css
  src/components/common/modal/overlay-container/OverlayContainer.tsx
Labels: 📁 컴포넌트

#51 #43 공통 컴포넌트 프로필 이미지, 리액트 버전 다운그레이드
  .gitignore
  next.config.ts
  package-lock.json
  package.json
  public/images/img_profiledefault.svg
  src/components/common/userprofile/UserProfile.module.css
  src/components/common/userprofile/UserProfile.tsx
  src/components/common/userprofile/test_UserProfile.tsx
Labels: 📁 컴포넌트

#57 #29 공통컴포넌트 input제목 마감일 등
  .prettierrc
  package-lock.json
  package.json
  src/components/common/input/CommentInput.module.css
  src/components/common/input/CommentInput.tsx
  src/components/common/input/DeadlineInput.module.css
  src/components/common/input/DeadlineInput.tsx
  src/components/common/input/TitleTagInput.module.css
  src/components/common/input/TitleTagInput.tsx
  src/components/common/input/test_TitleTagInput.tsx
Labels: 📁 컴포넌트

#58 페이지-메인페이지
  package-lock.json
  package.json
  public/images/.gitkeep
  public/images/img_landingimage1.svg
  public/images/img_landingimage2.svg
  public/images/img_landingimage3.svg
  public/images/img_landingimage4.svg
  public/images/img_landingimage5.svg
  public/images/img_landingimage6.svg
  public/images/img_whitelogo.svg
  public/images/img_whitetextlogo.svg
  src/components/common/button/.gitkeep
  src/components/product/landing/.gitkeep
  src/components/product/landing/BottomMain.module.css
  src/components/product/landing/BottumMain.tsx
  src/components/product/landing/Header.module.css
  src/components/product/landing/Header.tsx
  src/components/product/landing/Main.module.css
  src/components/product/landing/Main.tsx
  src/components/product/landing/NavBar.module.css
  src/components/product/landing/NavBar.tsx
  src/pages/home/.gitkeep
  src/pages/landing/index.tsx
Labels: ✨ 신규 기능

#62 #61 페이지네이션 버튼 추가공통
  src/components/common/button/Button.module.css
  src/components/common/button/CDSButton.tsx
  src/pages/test_button.tsx
  src/type/button.ts
Labels: 📁 컴포넌트

#63 #60 페이지 나의대시보드
  package-lock.json
  package.json
  src/components/common/sidebar/Sidebar.module.css
  src/components/common/sidebar/Sidebar.tsx
  src/lib/mydashboard/getInvitations.ts
  src/pages/mydashboard/index.tsx
  src/pages/mydashboard/mydashboard.module.css
  src/pages/test.tsx
  src/styles/globals.css
Labels: ✨ 신규 기능

#64 페이지_메인페이지
  src/components/product/landing/BottomMain.module.css
  src/components/product/landing/Footer.module.css
  src/components/product/landing/Footer.tsx
  src/components/product/landing/Header.module.css
  src/components/product/landing/Main.module.css
  src/components/product/landing/NavBar.tsx
  src/pages/index.tsx
  src/pages/landing/index.tsx
Labels: 💫 업데이트

#68 공통컴포넌트_돌아가기버튼
  src/components/common/button/ReturnButton.module.css
  src/components/common/button/ReturnButton.tsx
Labels: 📁 컴포넌트

#69 #54 페이지 로그인페이지
  public/images/img_signinlogo.svg
  src/components/common/input/AuthInput.module.css
  src/components/common/input/AuthInput.tsx
  src/constants/messages.ts
  src/lib/instance.ts
  src/lib/signin/postSignin.ts
  src/pages/signin/index.module.css
  src/pages/signin/index.tsx
  src/utils/authValidation.ts
Labels: ✨ 신규 기능

#71 💄 켄벤션에 맞춰 클래스명 변경
  src/components/common/input/auth-input/AuthInput.module.css
  src/components/common/input/auth-input/AuthInput.tsx
  src/components/common/input/auth-input/test_AuthInput.tsx
  src/components/common/modal/auth/AuthModal.module.css
  src/components/common/modal/auth/AuthModal.tsx
  src/components/common/modal/overlay-container/OverlayContainer.module.css
  src/components/common/modal/overlay-container/OverlayContainer.tsx
  src/components/common/userprofile/UserProfile.module.css
  src/components/common/userprofile/UserProfile.tsx
  src/components/common/userprofile/test_UserProfile.tsx
  src/pages/signin/index.module.css
  src/pages/signin/index.tsx
Labels: 💫 업데이트

#73 #66 페이지 나의대시보드
  src/components/common/button/Button.module.css
  src/components/common/sidebar/Sidebar.module.css
  src/components/common/sidebar/Sidebar.tsx
  src/components/product/mydashboard/.gitkeep
  src/components/product/mydashboard/DashboardList.module.css
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.module.css
  src/components/product/mydashboard/InvitationList.tsx
  src/lib/mydashboard/getInvitations.ts
  src/lib/mydashboard/putInvitations.ts
  src/pages/_app.tsx
  src/pages/mydashboard/.gitkeep
  src/pages/mydashboard/index.tsx
  src/styles/normalize.css
  src/utils/debounce.ts
Labels: 💫 업데이트

#74 #65 페이지 마이페이지
  package-lock.json
  package.json
  public/ic/ic_imgplus.svg
  src/components/common/button/Button.module.css
  src/components/common/button/ReturnButton.module.css
  src/components/common/input/info-input/CommentInput.module.css
  src/components/common/input/info-input/CommentInput.tsx
  src/components/common/input/info-input/DeadlineInput.module.css
  src/components/common/input/info-input/DeadlineInput.tsx
  src/components/common/input/info-input/TitleTagInput.module.css
  src/components/common/input/info-input/TitleTagInput.tsx
  src/components/common/input/info-input/test_TitleTagInput.tsx
  src/components/product/mypage/ChangePassword.module.css
  src/components/product/mypage/ChangePassword.tsx
  src/components/product/mypage/Main.module.css
  src/components/product/mypage/Main.tsx
  src/components/product/mypage/ModifyProfile.module.css
  src/components/product/mypage/ModifyProfile.tsx
  src/components/product/mypage/ProfileImageInput.module.css
  src/components/product/mypage/ProfileImageInput.tsx
  src/components/product/mypage/ProfileInfoForm.module.css
  src/components/product/mypage/ProfileInfoForm.tsx
  src/components/product/mypage/ProfileModifyModal.tsx
  src/lib/mypage/changePassword.ts
  src/lib/mypage/modifyProfile.ts
  src/lib/mypage/uploadImage.ts
  src/pages/_app.tsx
  src/pages/mypage/index.module.css
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/redux/settingSlice.ts
  src/redux/store.ts
  src/styles/globals.css
  src/type/button.ts
  src/type/userInfo.ts
Labels: ✨ 신규 기능

#78 #77 대시보드 배지 컬러 수정
  src/components/common/button/CDSButton.tsx
  src/pages/test_button.tsx
  src/type/button.ts
Labels: 💫 업데이트

#80 #75 나의 대시보드 페이지 반응형 디자인
  src/components/common/sidebar/.gitkeep
  src/components/product/mydashboard/DashboardList.module.css
  src/components/product/mydashboard/InvitationList.module.css
  src/components/product/mydashboard/InvitationList.tsx
Labels: 💄 스타일

#79 #50 페이지 대시보드 상세
  src/components/common/button/Button.module.css
  src/components/common/chip/helper.ts
  src/components/dashboard/card/Card.module.css
  src/components/dashboard/card/Card.tsx
  src/components/dashboard/card/CardImage.tsx
  src/components/dashboard/column/Column.module.css
  src/components/dashboard/column/Column.tsx
  src/hooks/useColumnData.ts
  src/hooks/useIntersectionObserver.ts
  src/lib/dashboard/getCards.ts
  src/lib/dashboard/getColumns.ts
  src/pages/dashboard/Dashboard.module.css
  src/pages/dashboard/index.tsx
  src/type/card.ts
  src/type/column.ts
  src/utils/formatDate.ts
Labels: ✨ 신규 기능

#84 #81 모달 대시보드 생성
  package-lock.json
  package.json
  src/components/product/mydashboard/DashboardList.module.css
  src/components/product/mydashboard/DashboardList.tsx
  src/lib/mydashboard/postDashboard.ts
Labels: ✨ 신규 기능

#86 #82 대시보드 상세 페이지 api 연동
  src/components/common/button/CDSButton.tsx
  src/components/dashboard/card/Card.tsx
  src/components/dashboard/column/Column.tsx
  src/hooks/useColumnData.ts
  src/pages/dashboards/.gitkeep
  src/pages/dashboards/Dashboard.module.css
  src/pages/dashboards/[id].tsx
  src/type/column.ts
Labels: ♻️ 리팩토링, 💫 업데이트

#90 컬럼 생성, 수정 // 초대하기 모달
  src/components/common/modal/general/GeneralModal.module.css
  src/components/common/modal/general/GeneralModal.tsx
Labels: 📁 컴포넌트

#94 🩹 디렉토리 경로 변경
  src/pages/dashboard/.gitkeep
  src/pages/dashboard/Dashboard.module.css
  src/pages/dashboard/[id].tsx
Labels: ♻️ 리팩토링

#96 #85 공통 header 로그인 회원가입 랜딩 제외
  package-lock.json
  package.json
  public/favicon.ico
  src/components/common/button/NavButton.module.css
  src/components/common/button/NavButton.tsx
  src/components/common/invitedmember/InvitedMember.module.css
  src/components/common/invitedmember/InvitedMember.tsx
  src/components/common/navbar/Navbar.module.css
  src/components/common/navbar/Navbar.tsx
  src/lib/navbar/getNavbar.ts
  src/styles/globals.css
Labels: ✨ 신규 기능

#98 #92 모달 할 일 카드
  src/components/common/dropdown/Dropdown.module.css
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/modal/detail-cards/DetailCardModal.module.css
  src/components/common/modal/detail-cards/DetailCardModal.tsx
  src/components/common/modal/overlay-container/OverlayContainer.module.css
  src/components/common/userprofile/UserProfile.module.css
  src/components/dashboard/card/Card.module.css
  src/components/dashboard/card/Card.tsx
  src/components/dashboard/card/CardImage.tsx
  src/components/dashboard/column/Column.tsx
  src/components/dashboard/comment/Comment.module.css
  src/components/dashboard/comment/Comment.tsx
  src/hooks/useColumnData.ts
  src/hooks/useComments.ts
  src/hooks/useDropdown.ts
  src/hooks/useModal.ts
  src/lib/dashboard/deleteCard.ts
  src/lib/dashboard/deleteComment.ts
  src/lib/dashboard/getCardDetail.ts
  src/lib/dashboard/getComments.ts
  src/lib/dashboard/postComment.ts
  src/lib/dashboard/putComment.ts
  src/pages/dashboard/[id].tsx
  src/type/card.ts
  src/type/comment.ts
  src/utils/formatDate.ts
Labels: ✨ 신규 기능

#97 #95 페이지 나의대시보드
  next.config.ts
  src/components/common/sidebar/Sidebar.tsx
  src/components/product/mydashboard/DashboardList.module.css
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.module.css
  src/components/product/mydashboard/InvitationList.tsx
  src/hooks/useSidebar.ts
  src/lib/mydashboard/getDashboard.ts
  src/lib/mydashboard/getInvitations.ts
  src/lib/mydashboard/postDashboard.ts
  src/lib/mydashboard/putInvitations.ts
  src/redux/dashboardSlice.ts
  src/redux/store.ts
  src/type/dashboard.ts
Labels: ♻️ 리팩토링

#103 #101 사이드바 링크 및패스 활성화시 색 변경 구현
  src/components/common/sidebar/Sidebar.module.css
  src/components/common/sidebar/Sidebar.tsx
Labels: 💫 업데이트

#93 #59 페이지 대시보드 수정
  public/ic/ic_whitecheck.svg
  public/ic/ic_whiteplus.svg
  src/components/common/.gitkeep
  src/components/common/button/ReturnButton.module.css
  src/components/common/button/ReturnButton.tsx
  src/components/common/modal/.gitkeep
  src/components/common/userprofile/test_UserProfile.tsx
  src/components/product/edit/InviteTitle/InviteList.module.css
  src/components/product/edit/InviteTitle/InviteList.tsx
  src/components/product/edit/InviteTitle/InviteTitle.module.css
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/ColorSelector.module.css
  src/components/product/edit/MainTitle/ColorSelector.tsx
  src/components/product/edit/MainTitle/MainTitle.module.css
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/edit/MemberTitle/MemberList.module.css
  src/components/product/edit/MemberTitle/MemberList.tsx
  src/components/product/edit/MemberTitle/MemberTitle.module.css
  src/components/product/edit/MemberTitle/MemberTitle.tsx
  src/hooks/.gitkeep
  src/lib/editdashboard/deleteDashboards.ts
  src/lib/editdashboard/deleteDashboardsInvitations.ts
  src/lib/editdashboard/getDashboardsInvitation.ts
  src/lib/editdashboard/getMembers.ts
  src/lib/editdashboard/postInvitations.ts
  src/lib/editdashboard/putDashboards.ts
  src/pages/edit/edit.module.css
  src/pages/edit/index.tsx
  src/pages/signup/.gitkeep
  src/type/.gitkeep
  src/type/Color.ts
  src/type/edit_dashboard.ts
Labels: ♻️ 리팩토링, ✨ 신규 기능, 💄 스타일

#106 #105 카드 댓글 무한 스크롤 수정
  src/components/common/modal/detail-cards/DetailCardModal.tsx
  src/components/dashboard/column/Column.module.css
  src/components/dashboard/column/Column.tsx
  src/hooks/useIntersectionObserver.ts
Labels: 💫 업데이트

#107 #76 페이지 할 일 생성
  src/components/common/button/ReturnButton.module.css
  src/components/common/input/info-input/DeadlineInput.module.css
  src/components/common/input/info-input/DeadlineInput.tsx
  src/components/common/input/info-input/TitleTagInput.module.css
  src/components/common/input/info-input/TitleTagInput.tsx
  src/components/dashboard/column/Column.tsx
  src/components/product/dashboard/card/AssigneeSection.module.css
  src/components/product/dashboard/card/AssigneeSection.tsx
  src/components/product/dashboard/card/ButtonSection.module.css
  src/components/product/dashboard/card/ButtonSection.tsx
  src/components/product/dashboard/card/CardImageInput.module.css
  src/components/product/dashboard/card/CardImageInput.tsx
  src/components/product/dashboard/card/CreateCard.module.css
  src/components/product/dashboard/card/CreateCard.tsx
  src/components/product/dashboard/card/DescriptionInput.module.css
  src/components/product/dashboard/card/DescriptionInput.tsx
  src/components/product/dashboard/card/TagManager.module.css
  src/components/product/dashboard/card/TagManager.tsx
  src/components/product/dashboard/modify-card/ModifyCard.tsx
  src/components/product/mypage/Main.module.css
  src/hooks/useAssigneeSelector.ts
  src/hooks/useCardImageUploader.ts
  src/hooks/useColumnData.ts
  src/hooks/useMembers.ts
  src/lib/dashboard/cardImageUpload.ts
  src/lib/dashboard/getMembers.ts
  src/lib/dashboard/postCard.ts
  src/pages/mypage/index.module.css
  src/pages/mypage/index.tsx
  src/redux/store.ts
  src/type/member.ts
Labels: ✨ 신규 기능

#109 💄 사이드바 UI 깨짐 수정
  src/components/common/sidebar/Sidebar.module.css
Labels: 💄 스타일

#110 #104 기능 컬럼생성 수정
  package-lock.json
  src/components/common/modal/general/GeneralModal.tsx
  src/components/dashboard/column/Column.tsx
  src/lib/dashboard/deleteColumns.ts
  src/lib/dashboard/postColumns.ts
  src/lib/dashboard/putColumns.ts
  src/lib/mydashboard/getDashboard.ts
  src/lib/mydashboard/getInvitations.ts
  src/lib/mydashboard/postDashboard.ts
  src/lib/mydashboard/putInvitations.ts
  src/pages/dashboard/[id].tsx
  src/pages/mydashboard/index.tsx
  src/type/dashboard.ts
Labels: ✨ 신규 기능

#112 🐛 CreateCard Syntax 오류 수정
  src/components/dashboard/column/Column.tsx
Labels: 🐛 버그

#114 Navbar 마이페이지, 로그아웃 기능 추가 및 모달 오버레이 전체적으로 수정
  src/components/common/button/NavButton.module.css
  src/components/common/modal/auth/AuthModal.tsx
  src/components/common/modal/auth/Test_AuthModal.tsx
  src/components/common/modal/delete-cards/DeleteCardsModal.tsx
  src/components/common/modal/delete-cards/Test_DeleteCardsModal.tsx
  src/components/common/modal/general/GeneralModal.module.css
  src/components/common/modal/general/GeneralModal.tsx
  src/components/common/navbar/Navbar.module.css
  src/components/common/navbar/Navbar.tsx
  src/components/dashboard/column/Column.tsx
  src/components/product/auth/SigninForm.tsx
  src/components/product/auth/SignupForm.tsx
  src/components/product/mypage/ChangePassword.tsx
  src/components/product/mypage/ProfileModifyModal.tsx
  src/pages/dashboard/Dashboard.module.css
  src/pages/dashboard/[id].tsx
Labels: ♻️ 리팩토링

#115 💄 대시보드 없을때 표시
  src/components/common/sidebar/Sidebar.tsx
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.module.css
  src/components/product/mydashboard/InvitationList.tsx
Labels: 💄 스타일, 💫 업데이트

#118 ✨ 초대하기 기능 구현
  src/components/common/navbar/Navbar.tsx
  src/lib/invite/postInvite.ts
Labels: ✨ 신규 기능

#119 ♻️ 컴포넌트 및 로직 분리
  src/components/common/modal/detail-cards/AuthorSection.module.css
  src/components/common/modal/detail-cards/AuthorSection.tsx
  src/components/common/modal/detail-cards/ChipSection.module.css
  src/components/common/modal/detail-cards/ChipSection.tsx
  src/components/common/modal/detail-cards/CommentSection.module.css
  src/components/common/modal/detail-cards/CommentSection.tsx
  src/components/common/modal/detail-cards/DetailCardModal.module.css
  src/components/common/modal/detail-cards/DetailCardModal.tsx
Labels: ♻️ 리팩토링

#121 #100 페이지 로그인페이지
  src/components/common/navbar/Navbar.tsx
  src/components/product/auth/SigninForm.tsx
  src/hooks/useAuthRedirect.ts
  src/lib/instance.ts
  src/pages/index.tsx
  src/pages/signin/index.module.css
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/redux/store.ts
Labels: ♻️ 리팩토링, ✨ 신규 기능

#124 #123 카드 이미지 확장자 제한
  src/components/product/dashboard/card/CardImageInput.tsx
  src/hooks/useCardImageUploader.ts
Labels: 💫 업데이트

#125 Dashboard 삭제기능
  src/components/common/dropdown/.gitkeep
  src/components/common/input/.gitkeep
  src/components/common/navbar/.gitkeep
  src/components/common/navbar/Navbar.tsx
  src/components/product/auth/.gitkeep
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/lib/editdashboard/deleteDashboards.ts
  src/lib/editdashboard/deleteDashboardsInvitations.ts
  src/lib/editdashboard/postInvitations.ts
  src/lib/editdashboard/putDashboards.ts
  src/lib/invite/postInvite.ts
  src/pages/dashboard/.gitkeep
  src/pages/dashboard/[id]/edit.module.css
  src/pages/dashboard/[id]/edit.tsx
Labels: ✨ 신규 기능

#126 페이지 대시보드 수정
  src/components/product/dashboard/.gitkeep
  src/components/product/edit/InviteTitle/InviteList.module.css
  src/components/product/edit/InviteTitle/InviteList.tsx
  src/components/product/edit/InviteTitle/InviteTitle.module.css
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/ColorSelector.tsx
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/edit/MemberTitle/MemberList.module.css
  src/components/product/edit/MemberTitle/MemberList.tsx
  src/components/product/edit/MemberTitle/MemberTitle.module.css
  src/components/product/edit/MemberTitle/MemberTitle.tsx
  src/lib/editdashboard/deleteDashboardsInvitations.ts
  src/lib/editdashboard/deleteMembers.ts
  src/lib/editdashboard/getDashboardsInvitation.ts
  src/lib/editdashboard/getInvitation.ts
  src/lib/editdashboard/getMembers.ts
  src/lib/editdashboard/postInvitations.ts
  src/lib/editdashboard/putDashboards.ts
  src/pages/dashboard/[id]/edit.tsx
  src/type/edit_dashboard.ts
Labels: ✨ 신규 기능

#128 Navbar적용 & 타입오류해결
  src/pages/dashboard/[id]/edit.module.css
  src/pages/dashboard/[id]/edit.tsx
Labels: ♻️ 리팩토링, ✨ 신규 기능

#129 #127 request body에 tag 색상 반영하도록 수정
  src/components/common/chip/Chip.tsx
  src/components/common/chip/helper.ts
  src/components/common/modal/detail-cards/ChipSection.tsx
  src/components/dashboard/card/Card.tsx
  src/components/product/dashboard/card/TagManager.tsx
  src/type/chip.ts
Labels: 💫 업데이트

#130 ♻️ 페이지네이션 버튼 수정
  src/components/common/sidebar/Sidebar.tsx
  src/components/product/mydashboard/DashboardList.tsx
Labels: ♻️ 리팩토링, 💫 업데이트

#131 페이지 대시보드 수정과 랜딩페이지 className 컨벤션으로 수정
  src/components/product/edit/InviteTitle/InviteTitle.module.css
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/MainTitle.module.css
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/edit/MemberTitle/MemberTitle.module.css
  src/components/product/edit/MemberTitle/MemberTitle.tsx
  src/components/product/landing/BottomMain.module.css
  src/components/product/landing/BottumMain.tsx
  src/components/product/landing/Footer.module.css
  src/components/product/landing/Footer.tsx
  src/components/product/landing/Header.module.css
  src/components/product/landing/Header.tsx
  src/components/product/landing/Main.module.css
  src/components/product/landing/Main.tsx
  src/components/product/landing/NavBar.module.css
  src/components/product/landing/NavBar.tsx
  src/components/product/mypage/.gitkeep
  src/pages/dashboard/[id]/edit.module.css
  src/pages/dashboard/[id]/edit.tsx
  src/utils/.gitkeep
Labels: ♻️ 리팩토링, 💄 스타일

#133 #99 페이지 할 일 수정
  public/ic/ic_grayCheck.svg
  src/components/common/input/info-input/DeadlineInput.tsx
  src/components/common/modal/detail-cards/DetailCardModal.tsx
  src/components/dashboard/card/Card.tsx
  src/components/dashboard/column/Column.tsx
  src/components/product/dashboard/create-card/AssigneeSection.module.css
  src/components/product/dashboard/create-card/AssigneeSection.tsx
  src/components/product/dashboard/create-card/ButtonSection.module.css
  src/components/product/dashboard/create-card/ButtonSection.tsx
  src/components/product/dashboard/create-card/CardImageInput.module.css
  src/components/product/dashboard/create-card/CardImageInput.tsx
  src/components/product/dashboard/create-card/CreateCard.module.css
  src/components/product/dashboard/create-card/CreateCard.tsx
  src/components/product/dashboard/create-card/DescriptionInput.module.css
  src/components/product/dashboard/create-card/DescriptionInput.tsx
  src/components/product/dashboard/create-card/TagManager.module.css
  src/components/product/dashboard/create-card/TagManager.tsx
  src/components/product/dashboard/modify-card/ColumnTitleSection.module.css
  src/components/product/dashboard/modify-card/ColumnTitleSection.tsx
  src/components/product/dashboard/modify-card/ModifyButtonSection.module.css
  src/components/product/dashboard/modify-card/ModifyButtonSection.tsx
  src/components/product/dashboard/modify-card/ModifyCard.module.css
  src/components/product/dashboard/modify-card/ModifyCard.tsx
  src/hooks/useAssigneeSelector.ts
  src/hooks/useCardImageUploader.ts
  src/hooks/useColumnData.ts
  src/hooks/useModifyButtonState.ts
  src/lib/dashboard/putCard.ts
  src/lib/dashboard/putCardSubmit.ts
  src/redux/cardListSlice.ts
  src/redux/cardSlice.ts
  src/redux/store.ts
  src/type/card.ts
Labels: ✨ 신규 기능

#134 페이지 대시보드 수정-지적사항 수정
  public/images/img_landingimage1.svg
  public/images/img_textlogo.svg
  src/components/product/edit/InviteTitle/InviteList.module.css
  src/components/product/edit/InviteTitle/InviteTitle.module.css
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/edit/MemberTitle/MemberList.module.css
  src/components/product/edit/MemberTitle/MemberTitle.module.css
  src/components/product/landing/BottomMain.module.css
  src/components/product/landing/Footer.module.css
  src/components/product/landing/Footer.tsx
  src/components/product/landing/Header.module.css
  src/components/product/landing/Main.module.css
  src/components/product/landing/NavBar.module.css
  src/pages/dashboard/[id]/edit.module.css
Labels: ♻️ 리팩토링, 💄 스타일

#139 #135 할 일 수정 redu로 업데이트
  src/components/dashboard/column/Column.tsx
  src/components/product/dashboard/modify-card/ModifyCard.tsx
  src/components/product/mypage/Main.module.css
  src/lib/dashboard/putCardSubmit.ts
  src/redux/cardListSlice.ts
  src/redux/renderSlice.ts
  src/redux/store.ts
Labels: 🐛 버그

#141 #136 1차 테스트 이슈 수정
  src/components/common/button/NavButton.module.css
  src/components/common/checkbox/CheckBox.module.css
  src/components/common/input/auth-input/AuthInput.module.css
  src/components/common/modal/auth/AuthModal.module.css
  src/components/common/modal/delete-cards/DeleteCardsModal.module.css
  src/components/common/navbar/Navbar.module.css
  src/components/common/navbar/Navbar.tsx
  src/components/common/userprofile/UserProfile.module.css
  src/components/product/auth/SigninForm.tsx
  src/components/product/auth/SignupForm.tsx
  src/pages/signin/index.module.css
  src/styles/globals.css
Labels: ♻️ 리팩토링, 🐛 버그, 🧪 테스트

#142 #138 할 일 카드 모달 이슈 수정
  src/components/common/chip/Chip.module.css
  src/components/common/modal/detail-cards/ChipSection.module.css
  src/components/common/modal/detail-cards/ChipSection.tsx
  src/components/common/modal/detail-cards/DetailCardModal.module.css
  src/components/dashboard/card/Card.module.css
  src/components/dashboard/card/CardImage.tsx
  src/components/dashboard/column/Column.module.css
  src/components/dashboard/column/Column.tsx
  src/components/product/dashboard/modify-card/ColumnTitleSection.module.css
  src/components/product/dashboard/modify-card/ColumnTitleSection.tsx
Labels: ♻️ 리팩토링, 🐛 버그, 💫 업데이트

#144 ✨ 메인 렌딩 페이지 스크롤 애니메이션 적용
  package-lock.json
  package.json
  src/components/product/landing/BottumMain.tsx
  src/components/product/landing/Header.tsx
  src/components/product/landing/Main.tsx
  src/styles/globals.css
Labels: ✨ 신규 기능

#147 ✨ 드롭다운 외부 영역 클릭 이벤트 추가
  src/components/common/dropdown/Dropdown.tsx
Labels: ♻️ 리팩토링, ✨ 신규 기능

#151 #148 skeleton UI 적용
  src/components/common/modal/detail-cards/DetailCardModal.module.css
  src/components/dashboard/card/SkeletonCard.module.css
  src/components/dashboard/card/SkeletonCard.tsx
  src/components/dashboard/column/Column.tsx
  src/components/dashboard/column/SkeletionColumn.module.css
  src/components/dashboard/column/SkeletonColumn.tsx
  src/hooks/useColumnData.ts
  src/pages/dashboard/[id].tsx
Labels: ✨ 신규 기능, 💫 업데이트

#154 #152 드롭다운 이벤트 타입 수정
  src/components/common/dropdown/Dropdown.tsx
Labels: ♻️ 리팩토링, 🐛 버그

#153 #140 할 일 생성 모달 이슈 수정
  package-lock.json
  package.json
  src/components/common/input/info-input/DeadlineInput.module.css
  src/components/common/input/info-input/DeadlineInput.tsx
  src/components/common/modal/detail-cards/DetailCardModal.tsx
  src/components/common/modal/overlay-container/OverlayContainer.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/sidebar/Sidebar.tsx
  src/components/dashboard/column/Column.tsx
  src/components/product/auth/SignupForm.tsx
  src/components/product/dashboard/create-card/AssigneeSection.module.css
  src/components/product/dashboard/create-card/AssigneeSection.tsx
  src/components/product/dashboard/create-card/CreateCard.module.css
  src/components/product/dashboard/create-card/CreateCard.tsx
  src/components/product/dashboard/create-card/DescriptionInput.module.css
  src/components/product/dashboard/create-card/TagManager.module.css
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.tsx
  src/hooks/useCardImageUploader.ts
  src/lib/dashboard/putCardSubmit.ts
  src/pages/_app.tsx
  src/pages/dashboard/[id].tsx
  src/styles/customToastStyles.module.css
Labels: ♻️ 리팩토링, 🐛 버그, 💫 업데이트

#156 input focus 통일
  src/components/common/input/auth-input/AuthInput.module.css
  src/components/common/input/info-input/DeadlineInput.module.css
  src/components/common/navbar/Navbar.tsx
  src/components/common/sidebar/Sidebar.module.css
  src/components/product/dashboard/create-card/CreateCard.module.css
  src/components/product/dashboard/modify-card/ModifyCard.module.css
  src/styles/globals.css
Labels: ♻️ 리팩토링, 💄 스타일

#158 ✨ Mydashboard페이지 스켈레톤 추가
  package-lock.json
  src/components/common/userprofile/UserProfile.tsx
  src/components/product/mydashboard/DashboardList.module.css
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.module.css
  src/components/product/mydashboard/InvitationList.tsx
Labels: ♻️ 리팩토링, ✨ 신규 기능

#159 #155 마이페이지 이슈 수정
  public/ic/ic_imageDelete.svg
  src/components/common/sidebar/Sidebar.module.css
  src/components/common/sidebar/Sidebar.tsx
  src/components/product/mypage/ChangePassword.module.css
  src/components/product/mypage/ChangePassword.tsx
  src/components/product/mypage/ModifyProfile.tsx
  src/components/product/mypage/ProfileImageInput.module.css
  src/components/product/mypage/ProfileImageInput.tsx
  src/lib/mypage/modifyProfile.ts
  src/pages/mypage/index.module.css
Labels: ✨ 신규 기능, 🐛 버그, 💫 업데이트

#163 #157 대시보드 수정 리로드 이슈 수정
  src/components/product/edit/InviteTitle/InviteList.tsx
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/ColorSelector.tsx
  src/components/product/edit/MainTitle/MainTitle.module.css
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/pages/dashboard/[id]/edit.tsx
Labels: ♻️ 리팩토링

#161 페이지 대시보드 수정 - 초대내역, 구성원 style 수정
  package-lock.json
  src/components/product/edit/InviteTitle/InviteList.module.css
  src/components/product/edit/InviteTitle/InviteTitle.module.css
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MemberTitle/MemberList.module.css
  src/components/product/edit/MemberTitle/MemberTitle.module.css
Labels: ♻️ 리팩토링, 💄 스타일

#164 #160 404 not found 페이지
  public/images/img_404.svg
  src/pages/404.tsx
  src/styles/404.module.css
Labels: 📁 컴포넌트

#169 페이지 대시보드 수정 - 모달
  src/components/product/edit/InviteTitle/InviteList.module.css
  src/components/product/edit/InviteTitle/InviteList.tsx
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/MainTitle.module.css
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/edit/MemberTitle/MemberList.module.css
  src/components/product/edit/MemberTitle/MemberList.tsx
  src/pages/dashboard/[id]/edit.module.css
  src/pages/dashboard/[id]/edit.tsx
Labels: ✨ 신규 기능

#170 ✨ 401 에러 발생 시 로그인 페이지로 리다이렉트
  src/lib/instance.ts
Labels: 💫 업데이트, 📡 API

#172 대시보드수정페이지 - 멤버 삭제시 reload()대신 dispatch사용
  src/components/product/edit/MemberTitle/MemberList.tsx
  src/components/product/edit/MemberTitle/MemberTitle.tsx
Labels: ♻️ 리팩토링

#171 #166 할 일 수정 모달 이슈 수정
  src/components/common/input/info-input/DeadlineInput.tsx
  src/components/dashboard/card/Card.tsx
  src/components/product/dashboard/create-card/CreateCard.module.css
  src/components/product/dashboard/create-card/CreateCard.tsx
  src/components/product/dashboard/modify-card/ColumnTitleSection.module.css
  src/components/product/dashboard/modify-card/ColumnTitleSection.tsx
  src/components/product/dashboard/modify-card/ModifyCard.module.css
  src/components/product/dashboard/modify-card/ModifyCard.tsx
  src/lib/dashboard/putCardSubmit.ts
Labels: ♻️ 리팩토링, 🐛 버그, 💫 업데이트

#175 린트 적용 및 토스트 메시지 위치 조정
  .eslintrc.json
  src/components/common/checkbox/CheckBox.tsx
  src/components/common/input/auth-input/AuthInput.tsx
  src/components/common/input/auth-input/test_AuthInput.tsx
  src/components/common/invitedmember/InvitedMember.tsx
  src/components/common/modal/auth/Test_AuthModal.tsx
  src/components/common/modal/delete-cards/Test_DeleteCardsModal.tsx
  src/components/common/modal/detail-cards/DetailCardModal.tsx
  src/components/common/navbar/Navbar.tsx
  src/components/common/userprofile/UserProfile.tsx
  src/components/product/auth/SigninForm.tsx
  src/components/product/auth/SignupForm.tsx
  src/components/product/dashboard/create-card/AssigneeSection.tsx
  src/components/product/dashboard/create-card/CreateCard.tsx
  src/components/product/edit/InviteTitle/InviteList.tsx
  src/components/product/edit/InviteTitle/InviteTitle.tsx
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.tsx
  src/components/product/mypage/ChangePassword.tsx
  src/components/product/mypage/ModifyProfile.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/customToastStyles.module.css
  src/utils/authValidation.ts
Labels: ♻️ 리팩토링, 🐛 버그

#180 🐛 : 비밀번호 변경시 에러메세지 초기화
  src/components/product/mypage/ChangePassword.tsx
Labels: 🐛 버그

#176 페이지 대시보드 수정 - 모달창 외부 클릭시 종료
  src/components/product/edit/InviteTitle/InviteList.tsx
  src/components/product/edit/InviteTitle/InviteTitle.module.css
  src/components/product/edit/MainTitle/MainTitle.tsx
  src/components/product/edit/MemberTitle/MemberList.tsx
  src/components/product/landing/Footer.module.css
  src/pages/dashboard/[id]/edit.tsx
Labels: ♻️ 리팩토링, ✨ 신규 기능

#182 💄 컬럼, 할 일 모달 커스텀 스크롤 추가
  src/components/common/modal/detail-cards/DetailCardModal.module.css
  src/components/common/modal/detail-cards/DetailCardModal.tsx
  src/components/dashboard/column/Column.module.css
  src/components/dashboard/column/Column.tsx
Labels: 💄 스타일, 💫 업데이트

#185 페이지 대시보드 수정
  src/components/product/landing/NavBar.module.css
  src/components/product/landing/NavBar.tsx
  src/pages/index.tsx
Labels: ♻️ 리팩토링

#186 💄 대시보드 이름 길어지면 말줄임 처리
  src/components/common/button/Button.module.css
  src/components/product/mydashboard/DashboardList.module.css
  src/components/product/mydashboard/DashboardList.tsx
  src/components/product/mydashboard/InvitationList.module.css
  src/components/product/mydashboard/InvitationList.tsx
  src/lib/mydashboard/getInvitations.ts
Labels: 🐛 버그, 💄 스타일, 💫 업데이트
